const $ = (s) => document.querySelector(s);
let mode = "demo", draft = null, selected = null, photo = null, approval = null;
const placeholder = "data:image/svg+xml," + encodeURIComponent("<svg xmlns='http://www.w3.org/2000/svg' width='1080' height='1920'><rect width='100%' height='100%' fill='#26352f'/><text x='540' y='930' text-anchor='middle' fill='#e6dfcf' font-family='serif' font-size='54'>IL TIRATORE</text><text x='540' y='1000' text-anchor='middle' fill='#e6dfcf' font-family='sans-serif' font-size='25'>REFERENCE STORY MEDIA</text></svg>");
const trace = (title, detail, kind = "system") => { const item = document.createElement("li"); item.className = kind; item.innerHTML = `<strong>${title}</strong><span>${detail}</span>`; $("#trace").prepend(item); };
const api = async (url, payload = {}) => { trace("API request", `POST ${url}`, "api"); const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { trace("API rejected", data.error, "error"); throw new Error(data.error); } trace("Server state", `${data.state || "verified"} · draft ${data.draftId || "—"}`, "system"); return data; };
const withBusy = async (button, label, task) => { if (button.disabled) return; const original = button.textContent; button.disabled = true; button.textContent = label; try { await task(); } finally { button.disabled = false; button.textContent = original; } };
function resetDraftView() { draft = null; selected = null; approval = null; $("#interpretation-stage").classList.add("hidden"); $("#artefact-stage").classList.add("hidden"); $("#approval-record").classList.add("hidden"); $("#verify-result").textContent = ""; $("#directions").innerHTML = ""; $("#checks").innerHTML = ""; $("#story-caption").textContent = ""; }
function context() { return { mode, day: $("#day").value, temperatureC: +$("#temperature").value, forecastC: +$("#forecast").value, blockingEvents: +$("#events").value, recentPosts: +$("#recent-posts").value, opensAt: $("#opens-at").value, closesAt: $("#closes-at").value, products: $("#products").value.split(",").map((x) => x.trim()).filter(Boolean), media: photo }; }
function setMode(next) { mode = next; document.querySelectorAll(".mode-option").forEach((b) => { const selectedMode = b.dataset.mode === mode; b.classList.toggle("selected", selectedMode); b.setAttribute("aria-checked", String(selectedMode)); }); const live = mode === "live"; ["#day", "#temperature", "#forecast", "#events", "#recent-posts", "#opens-at", "#closes-at", "#products"].forEach((s) => $(s).disabled = live); $("#mode-description").textContent = live ? "Live reads weather, calendar and configured operations. Browser fields are deliberately ignored." : "Demo keeps its provenance visible: these are supplied scenario values, not live facts."; trace("Mode selected", live ? "Live source adapters will run." : "Deterministic reference engine will run."); }
document.querySelectorAll(".mode-option").forEach((b) => b.addEventListener("click", () => setMode(b.dataset.mode)));
$("#photo").addEventListener("change", (e) => { const file = e.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { photo = { filename: file.name, mimeType: file.type, dataUrl: reader.result }; $("#story-image").src = reader.result; trace("Media staged", `${file.name}; its SHA-256 will bind approval.`); }; reader.readAsDataURL(file); });
function showInterpretation() { const i = draft.interpretation; $("#interpretation-stage").classList.remove("hidden"); $("#observation").textContent = i.observation; $("#relevance").textContent = i.organisationalRelevance; $("#semantic-direction").textContent = i.semanticDirection; $("#evidence").textContent = i.contextEvidence.join(" · "); $("#rejected-frames").textContent = i.rejectedFrames.join(" · "); $("#avoid").textContent = i.avoid.join(" · "); $("#version-badge").textContent = `Attempt ${draft.interpretationAttempt || 1} · Philosophy ${draft.versions.philosophy} · Strategy ${draft.versions.strategy}`; trace("Interpretation ready", `Structured rationale attempt ${draft.interpretationAttempt || 1} is awaiting the first human gate.`, "model"); }
function renderChecks(direction) { const v = direction.validation, c = direction.semanticConformance; $("#checks").innerHTML = `<p class="${v.valid ? "pass" : "fail"}"><strong>Deterministic validation</strong> ${v.valid ? "passed" : [...v.missing, ...v.violations].join(" · ")}</p><p class="${c.conforms ? "pass" : "fail"}"><strong>Semantic conformance</strong> ${c.conforms ? "passed" : c.violations.join(" · ")}</p><ul>${(c.checks || []).map((x) => `<li>${x.passed ? "✓" : "×"} ${x.boundary}</li>`).join("")}</ul>`; $("#approve-artefact").disabled = !(v.valid && c.conforms); }
function renderDirections() { $("#artefact-stage").classList.remove("hidden"); $("#artefact-badge").textContent = `Skill ${draft.versions.skill} · Conformance ${draft.versions.conformancePolicy}`; const area = $("#directions"); area.innerHTML = ""; draft.directions.forEach((d, n) => { const b = document.createElement("button"); b.className = "direction"; b.innerHTML = `<strong>0${n + 1} · ${d.id}</strong><span>${d.concept}</span><small>Nearest avoid: ${d.nearestAvoid} · Risk: ${d.riskNote}</small>`; b.onclick = () => { selected = d; document.querySelectorAll(".direction").forEach((x) => x.classList.toggle("selected", x === b)); $("#story-caption").textContent = d.caption; $("#story-image").src = photo?.dataUrl || placeholder; renderChecks(d); trace("Direction selected", `${d.id}; server-generated candidate retained in the immutable draft.`); }; area.append(b); if (!n) b.click(); }); trace("Directions ready", "Creative stage ran only after interpretation approval.", "model"); }
$("#prepare").onclick = () => withBusy($("#prepare"), "Preparing…", async () => { try { resetDraftView(); $("#status").textContent = "Preparing…"; trace("Context builder", mode === "live" ? "Calling weather, calendar, operations, and publishing-history sources." : "Recording supplied scenario provenance.", "api"); draft = await api("/api/prepare", context()); $("#status").textContent = draft.opening.isOpen ? "Context verified. Review the interpretation." : "Operating gate closed; silence recorded."; if (!draft.opening.isOpen || draft.interpretation.recommendation === "do_not_publish") { trace("Silence decision", draft.interpretation.reason, "system"); return; } showInterpretation(); } catch (e) { $("#status").textContent = e.message; } });
$("#approve-interpretation").onclick = () => withBusy($("#approve-interpretation"), "Generating…", async () => { try { draft = await api(`/api/drafts/${draft.draftId}/interpretation/approve`, { decision: "approve", reason: "Reviewer approved the stated relevance." }); trace("Human gate one", "Publisher approved interpretation; creative work is now authorised.", "human"); draft = await api(`/api/drafts/${draft.draftId}/directions`); renderDirections(); } catch (e) { $("#status").textContent = e.message; } });
$("#iterate-interpretation").onclick = () => withBusy($("#iterate-interpretation"), "Iterating…", async () => { try { draft = await api(`/api/drafts/${draft.draftId}/interpretation/iterate`); trace("Human gate one", "Reviewer requested another bounded interpretation before authorising creative work.", "human"); showInterpretation(); } catch (e) { $("#status").textContent = e.message; } });
$("#stop").onclick = () => withBusy($("#stop"), "Recording…", async () => { try { draft = await api(`/api/drafts/${draft.draftId}/interpretation/approve`, { decision: "do_not_publish", reason: "Reviewer chose silence." }); $("#status").textContent = "Silence recorded."; trace("Human gate one", "Reviewer rejected interpretation and stopped execution.", "human"); } catch (e) { $("#status").textContent = e.message; } });
$("#cancel").onclick = () => withBusy($("#cancel"), "Cancelling…", async () => { try { draft = await api(`/api/drafts/${draft.draftId}/cancel`, { reason: "Reviewer cancelled artefact." }); $("#status").textContent = "Cancellation recorded."; trace("Human gate two", "Artefact cancelled; no approval token exists.", "human"); } catch (e) { $("#status").textContent = e.message; } });
$("#approve-artefact").onclick = () => withBusy($("#approve-artefact"), "Approving…", async () => { try { approval = await api(`/api/drafts/${draft.draftId}/artefact/approve`, { directionId: selected.id }); $("#approval-record").classList.remove("hidden"); $("#approval-hash").textContent = approval.canonicalHash; $("#approval-token").textContent = approval.approvalToken; $("#media-hash").textContent = approval.approvalManifest.mediaHash; trace("Approval token issued", "Server signed its stored interpretation, media, text, version and reviewer state.", "human"); } catch (e) { $("#status").textContent = e.message; } });
$("#verify-token").onclick = () => withBusy($("#verify-token"), "Verifying…", async () => { try { const result = await api("/api/verify", { approvalManifest: approval.approvalManifest, approvalToken: approval.approvalToken }); $("#verify-result").textContent = result.valid ? "Verified: exact stored state matches the token." : result.expired ? "Not verified: approval has expired." : "Verification failed."; trace("Token verification", result.valid ? "HMAC matches canonical manifest." : result.expired ? "Signature matches but approval has expired." : "Signature mismatch.", result.valid ? "system" : "error"); } catch (e) { $("#verify-result").textContent = e.message; } });
$("#architecture").innerHTML = ["Context → facts + provenance", "Philosophy → interpretation", "Human gate → approve relevance", "Creative Skill → candidates", "Validation + conformance", "Human gate → exact-state approval", "Audit → hash-chained events"].map((x) => `<div>${x}</div>`).join("");
$("#story-image").src = placeholder; setMode("demo"); trace("Reference ready", "Choose a mode and prepare a decision.");
